# Generated by Django 5.0.1 on 2026-02-18 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_remove_business_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner'], name='businesses__owner_i_7abb69_idx'),
        ),
    ]
